### PR TITLE
feat: render prompt result as markdown

### PR DESCRIPTION
**Pull request by tianweiliu**
- Added `vue3-markdown-it` as dependency
- Replaced `textarea` with `div` wrapper and `Markdown`

### CODE REVIEW

**Comment by chouch0u** [comment]
This project uses pnpm as the package manager. Please run `pnpm install` to install the packages and update the `pnpm-lock.yaml` file.

**Comment by chouch0u** [comment]
When scrolling up, the auto-scroll feature is not working properly.

https://github.com/webpilot-ai/Webpilot/assets/4880734/863889b9-3936-41bf-8e47-7af5f457af43

**Comment by tianweiliu** [comment]
@chouch0u Both should be fixed with the newest commit

**Comment by chouch0u** [comment]
> @chouch0u Both should be fixed with the newest commit

Horizontal scroll bar still exist ( test on windows).

image

**Pull request merged**
